### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.response]: Http status error [401]

### ISSUE THREAD

**Issue by polylymer** [Madfix-me/CloudNet-App#24]
### Stacktrace

```
E/flutter (13685): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: DioError [DioErrorType.response]: Http status error [401]
E/flutter (13685): Source stack:
E/flutter (13685): #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488:35)
E/flutter (13685): #1      DioMixin.request (package:dio/src/dio_mixin.dart:483:12)
E/flutter (13685): #2      DioMixin.requestUri (package:dio/src/dio_mixin.dart:437:12)
E/flutter (13685): #3      DioMixin.postUri (package:dio/src/dio_mixin.dart:118:12)
E/flutter (13685): #4      LoginHandler.handleLogin (package:cloudnet/feature/login/login_handler.dart:65:10)
E/flutter (13685): #5      _LoginPageState.login (package:cloudnet/feature/login/login_page.dart:99:12)
E/flutter (13685): #6      _LoginPageState.build.<anonymous closure>.<anonymous closure> (package:cloudnet/feature/login/login_page.dart:83:38)
E/flutter (13685): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
E/flutter (13685): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
E/flutter (13685): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
E/flutter (13685): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
E/flutter (13685): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:232:7)
E/flutter (13685): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
E/flutter (13685): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
E/flutter (13685): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
E/flutter (13685): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
E/flutter (13685): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
E/flutter (13685): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
E/flutter (13685): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
E/flutter (13685): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
E/flutter (13685): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
E/flutter (13685): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
E/flutter (13685): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
E/flutter (13685): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
E/flutter (13685): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
E/flutter (13685): #25     _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (13685): #26     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (13685): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (13685): #28     _invoke1 (dart:ui/hooks.dart:170:10)
E/flutter (13685): #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
E/flutter (13685): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
E/flutter (13685): 
E/flutter (13685): #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:643:7)
E/flutter (13685): #1      _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter (13685): #2      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (13685): #3      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (13685): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter (13685): #5      Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter (13685): #6      Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (13685): #7      _SyncCompleter._completeError (dart:async/future_impl.dart:51:12)
E/flutter (13685): #8      _Completer.completeError (dart:async/future_impl.dart:23:5)
E/flutter (13685): #9      Future.any.onError (dart:async/future.dart:616:45)
E/flutter (13685): #10     _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter (13685): #11     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (13685): #12     _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (13685): #13     Future._propagateToListeners.handleError (dart:async/future_impl.dart:778:47)
E/flutter (13685): #14     Future._propagateToListeners (dart:async/future_impl.dart:799:13)
E/flutter (13685): #15     Future._completeError (dart:async/future_impl.dart:574:5)
E/flutter (13685): #16     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:665:7)
E/flutter (13685): #17     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (13685): #18     _CustomZone.r
```

### Actions to reproduce

when i'm trying to login after typing in my username + password and I press the login button nothing happens and this error occurs 

### CloudNet version

CloudNet Blizzard 4.0.0-SNAPSHOT 3d21f577 created by Dytanic, maintained by the CloudNet Community
[29.07 18:21:15.944] INFO: Discord: <https://discord.cloudnetservice.eu/>
[29.07 18:21:15.944] INFO:
[29.07 18:21:15.945] INFO: ClusterId: 4a44726f-****-4922-****-d2ffd48ca8d9
[29.07 18:21:15.945] INFO: NodeId: Node-OIS3
[29.07 18:21:15.946] INFO: Head-NodeId: Node-OIS3
[29.07 18:21:15.946] INFO: CPU usage: (P/S) 8/12/100%
[29.07 18:21:15.947] INFO: Node services memory allocation (U/R/M): 0/0/11464 MB
[29.07 18:21:15.947] INFO: Threads: 24
[29.07 18:21:15.948] INFO: Heap usage: 36/256MB
[29.07 18:21:15.948] INFO: JVM: Debian 17 (OpenJDK 64-Bit Server VM 17.0.4+8-Debian-1deb11u1)
[29.07 18:21:15.949] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: unstable/rewrite

### Other

I don't know if it's a bug with the app or if I missconfigured cloudnet, but I don't know what's wrong

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by TheMeinerLP** [comment]
Thats to reporting the bug. Which branch you are using ?
And have you set a password to that user ?

**Comment by polylymer** [comment]
> I guess I used the default branch which is currently develop. I used the beta script to run the app, but it looks like the alpha script gives the same error. I created the user with the `permission create user <myUsername> <myPassword> <potency>` command.
If more information is needed just let me know.

**Comment by TheMeinerLP** [comment]
Have you added the user the permission * ?
You need for login also permissions.

**Comment by polylymer** [comment]
No, the user had no permissions, that could be the problem. I'll try it tomorrow with permissions and report back if it worked. It would be cool if a popup or something similar would open up in the future in the event of such an error, but I also know that this project is in the alpha/public beta, so see it as a suggestion.

**Comment by TheMeinerLP** [comment]
Thats already planned. But CloudNet don't have a different error code for wrong permission or unsuccessfully login or else yet.

**Comment by polylymer** [comment]
after i gave my user the * permission, the login process worked fine. But at the moment there are no functions implemented, right? The only thing that should be implemented according to the readme is the setup routine of tasks/templates. After I pressed the + button from the Tasks category, the steps worked up to step 7 where I should select the task environment. However, the dropdown button does not work there and the keyboard cannot be used there either. So you are stuck at step 7. If you want, I can also open a new issue if the problem is not yet known.

**Comment by TheMeinerLP** [comment]
A new issue would be fine. 
Some function are implemented but unfortunately there is no existing list for already implemented functions because it isn't created yet. 
Function which work:
- Create task
- Edit task
- Delete task
- View task category.  
- Multi Node Login

Function which **not** work:
- Create category
- Delete category

**Comment by TheMeinerLP** [comment]
Can i close this issue ?
